frequency: 20
imu0: /imu/data
imu0_config: [false, false, false,
            true, true, true,
            false, false, false,
            true, true, true,
            true, true, true]

imu0_differential: false

imu0_remove_gravitational_acceleration: true

odom_frame: odom
base_link_frame: base
world_frame: odom
