frequency: 40
imu0: /nav/filtered_imu/data
imu0_config: [false, false, false,
            true, true, true,
            false, false, false,
            true, true, true,
            false, false, false]

imu0_differential: false

odom_frame: odom
base_link_frame: base
world_frame: odom
