frequency: 40
odom0: /nav/odom
odom0_config: [false, false, false,
            true, true, true,
            false, false, false,
            true, true, true,
            false, false, false]

odom0_differential: false

odom_frame: odom
base_link_frame: base
world_frame: odom
